require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**.rb

RSpec/MultipleExpectations:
  Enabled: false